# fly.toml app configuration file generated for host-langflow-jlitsq on 2025-08-22T03:07:12Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'host-langflow-jlitsq'
primary_region = 'lax'

[build]

[http_service]
  internal_port = 7860
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 2048
